version: '3'
services:
  uniplato:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
  uniplato-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command:
      - yarn
      - test